### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by antonkarliner** [mayflower/PayForMe#11]
Just wanted to ask about the release date, so that one can save it to the calendar and download the App ASAP.

**Comment by Hustenbonbon** [comment]
Hey Anton, I just hit the release button, now we need to wait for the Appstore to do its caching, afterwards click on this link on your iPhone: https://apps.apple.com/us/app/payforme/id1500428306?l=de&ls=1

**Comment by antonkarliner** [comment]
Works! Thanks a lot!
