### ISSUE TITLE
Allow iHateMoney projects with different backends

### ISSUE THREAD

**Issue by Hustenbonbon** [mayflower/PayForMe#13]

**Comment by Hustenbonbon** [comment]
iHateMoney is not under active development anymore, and it looks like it is a rather dead project to me. Using the public instance as a easy tryout backend seems reasonable to me, but providing the functionality for custom backends doesn't seem effective to me.
Please comment if you have a need for this.

**Comment by m-idler** [comment]
See https://github.com/mayflower/PayForMe/pull/30
