### ISSUE TITLE
Feature request: ability to change currency

### ISSUE THREAD

**Issue by antonkarliner** [mayflower/PayForMe#15]
Would be great to have an ability to change project currency in settings. At the moment all the bills are in Euro.

**Comment by Hustenbonbon** [comment]
Actually backendwise, there do not exist any currencies, just numbers. So yeah, would be not a big task - will try to get it done soonTM

**Comment by Hustenbonbon** [comment]
So I had a look at cospend - there are no currencies there :-D
I removed the € sign until I find the time to integrate a currency into the model of a project, along with the possibility to decide the currency when creating a project. as we already went live, this would mean a database migration if I do it that way, or old projects remain € projects - there is no way yet to edit a project. 
Haven't decided yet on how to tackle that issue, thoughts welcome

**Comment by edwardscaleb9** [comment]
I think since cospend doesn't have a currency, no currency would be fine for me!

**Comment by Hustenbonbon** [comment]
Just released new version with no currency
