### ISSUE TITLE
Change "project name" to "project id"

### ISSUE THREAD

**Issue by antonkarliner** [mayflower/PayForMe#16]
When adding a Cospend project you're asked to provide "project name" and password. However, there are two different variables in Cospend, "project id", which you actually need to connect to your project and "name", which is displayed in Cospend. So, that could be misleading when importing a project in PayForMe, maybe consider changing it.
<img width="293" alt="Снимок экрана 2020-03-21 в 00 47 49" src="https://user-images.githubusercontent.com/19594480/77208840-c873ca80-6b0d-11ea-8321-423f415c75c9.png">

**Comment by Hustenbonbon** [comment]
Fixed in master, will be part of next release. Thanks!
