### ISSUE TITLE
Translate to other languages

### ISSUE THREAD

**Issue by antonkarliner** [mayflower/PayForMe#17]
I will be happy to help to translate PayForMe to Russian and German.

**Comment by Hustenbonbon** [comment]
Thanks! I will look in localization as fast as possible, so you can get started working on :-)

**Comment by antonkarliner** [comment]
Maybe use Transifex: https://www.transifex.com

**Comment by Hustenbonbon** [comment]
Thanks, I had a look into transifex and I didn't like it that much from first sight to be honest, but didn't look deep in int.
BUT:
I hab a look on how localization can be done in SwiftUI, and it is basically very easy. I added 3 files: 
```
Strings/de.lproj/Localizable.strings
Strings/en.lproj/Localizable.strings
Strings/ru.lproj/Localizable.strings
```
Now, everything that needs to be done, is write the translation into each of the files in a manner of
`"Enter project name" = "Bitte Projektname eingeben";` into the respective file, and everywhere the left text occurs in a view, it will be switched out by the right one. Can you work with that? My time is a bit short right now unfortunately, but would be great to have that!

**Comment by antonkarliner** [comment]
OK! Added PR for Russian.

**Comment by Hustenbonbon** [comment]
Wow, that was fast! Are you on matrix btw? then I would be happy to get in contact with you: @max.tharr:matrix.mayflower.de

**Comment by antonkarliner** [comment]
Never tried it actually, but will look into it in the following days, as I've heard about it a lot. Speaking of federated services, I use Nextcloud Talk.
