### ISSUE TITLE
Add Bill date

### ISSUE THREAD

**Issue by antonkarliner** [mayflower/PayForMe#19]
Sometimes you forget to add the bill on the same day, it would be useful to have an ability to add a date to the bill, especially since such option exists in Cospend.

**Comment by CrysK** [comment]
Hi, I see that you closed the merge of the date implementation: 
https://github.com/mayflower/PayForMe/pull/59

Is there a way to have the latest version w/ this feature? ☺

**Comment by Hustenbonbon** [comment]
HI, I never got any feedback from beta testers so far, and didn't want to release a potentially broken version. 
I tested it myself though and released now anyway, the new version with setting a bill date is on the way and currently in Apple's review. Should be out in a day hopefully.

There is however a beta test link, if you want to check last minute: https://testflight.apple.com/join/o6XAnU9g

**Comment by CrysK** [comment]
It works great, thanks for this. Please close.
