### ISSUE TITLE
Can't add Nextcloud(Cospend) Server with subdomain

### ISSUE THREAD

**Issue by messma** [mayflower/PayForMe#20]
Is it possibile to add a cospend server with a subdomain?
eg. subdomain.domain.net
Can someone check this for me?
Maybe there is an other fault.

**Comment by Hustenbonbon** [comment]
you mean like cloud.domain.net? I tested with this pattern. If it is not working for your cloud, if you create a testproject for me on your nextcloud, I can have a look, if it works for me

**Comment by messma** [comment]
Yes like cloud.domain.net.
i created a Project for you on my cloud.
Domain: https://xnzxut6ib8dshkrs.myfritz.net
Name/ID: 2
PW: Test1234!
Please tell me when you tested it. 
I'm not feeling safe to expose these Data here.

**Comment by Hustenbonbon** [comment]
Saved the credentials and could verify, that it does not work. Will look into it.
You can remove the credentials now

**Comment by Hustenbonbon** [comment]
So, the problem was that we currently have a bug preventing passwords with capital letters to work. Fixed it locally, will try to release that soon.
Until then, try it with a password with no capital letters, then it will work!

Thanks for using (or trying to use) PayForMe!

**Comment by cernoel** [comment]
i have a similar problem, but i have "https://myownserver.duckdns.org/nextcloud/" as server (nginx reverse proxy). i can access the shared link and so on, but the app does not want to communicate with my server, it does not even show an error. what can i do?

**Comment by Hustenbonbon** [comment]
@cernoel do you use a capital letter in your password? If yes, please try if it works without capital letters. A fix for that is already in appstore review and should be released soon.
If not, please create a test project for me on your server, and send me the details per mail (in my profile). Then I'll have a look. 
Although we coded it in a way it should work when the nextcloud is not in the root directory of the domain, we did get to test that yet.

**Comment by cernoel** [comment]
i've tried these cases and it works when i am using lowercase id, name and password, you are right.
