### ISSUE TITLE
Case sensitive and basic requirements to add project

### ISSUE THREAD

**Issue by clay9247** [mayflower/PayForMe#22]
I noticed two things adding my project for the first time:

1. If you use a case sensitive project name and/or password for your project in Cospend you can enter these settings in the PayForMe. These settings will however be translated into lower case when establishing the link to Cospend. This will produce a 401 unauthorized response and nothing will proceed in PayForMe. MoneyBuster sends the settings in case senstitive:

```
Example (Project Name: Test. Password: Test)

"GET //index.php/apps/cospend/api/projects/test/test/members HTTP/1.1" 401 33 "-" "PayForMe/36 CFNetwork/1121.2.2 Darwin/19.3.0"
"GET /index.php/apps/cospend/api/projects/Test/Test/members HTTP/1.1" 200 229 "-" "MoneyBuster/0.0.19"
```

When changing all settings to lower case the project can be successfully added. 

2. If minimum requirements are not met the project can also not be added. It seems like at least one user has to be added in Cospend before the project can be added to PayForMe, as the "members" page that is initially requested is empty and PayForMe does not proceed.

3. It would be great if PayForMe could give some information why the project is not added (e.g. the response codes ). At the moment the only way you know if everything is OK is when the add button turns form grey to blue.

Nextcloud 18.0.3
Cospend 0.4.2
PayForMe/36 CFNetwork/1121.2.2 Darwin/19.3.0
MoneyBuster/0.0.19

**Comment by Hustenbonbon** [comment]
Hey, 
thanks for the issue! 
1. This is right, maybe related to #16 ? We actually use the project id, which I assumed to be the Project Name but mowercased without special characters. From your issue it looks like this was a false assumption. Will look into it.
2. This is right, and I should definitely change that - currently at least one member is required.
3. Sounds reasonable - will look into it

**Comment by Hustenbonbon** [comment]
1. Password was lowercased for some reason. I removed that.
2. Minimum member count removed - now it will be accepted if the http code is 200
3. For server not reachable and unauthorized errors, error messages got added, for others a generic text plus response code

I'm trying to fix a nasty UI bug that came on the way, and will make a new release in the next days

**Comment by Hustenbonbon** [comment]
Fixed in current master

**Comment by Hustenbonbon** [comment]
After another bug preventing a new release fixed yesterday, hopefully coming in the next days finally

**Comment by Hustenbonbon** [comment]
Just released fixed version!
