### ISSUE TITLE
pasting text on "Server Address" field

### ISSUE THREAD

**Issue by 3tyh86qvt** [mayflower/PayForMe#27]
problem: unable to paste the server address on the "Server Address" field.

Tried to type the whole URL by hand. Sadly, the view doesn't scroll and I would have to type the characters blindly

**Comment by Hustenbonbon** [comment]
Hey, sorry, that sucks! Which device are you using? Maybe we neglected smaller device.
A screenshot would be super helpful!

I'll definitely add a scrolling functionality, and the pasting should also be possible to integrate, I am wondering why it doesn't work just by itself

**Comment by 3tyh86qvt** [comment]
i'm using an iphone 6s…

i'm unable to connect to the sever "could not find server" :/
i've been able to connect through android, though 

Thank you very much! 👯

**Comment by Hustenbonbon** [comment]
Oh, only type in 192.168.5.263 on the current version, now I understand the scrolling problem. Definitely gave me some insight, unfortunately pasting isn't as easy as it should be with swiftui :-(

**Comment by 3tyh86qvt** [comment]
https://youtu.be/IuHVZByd8aQ

**Comment by Hustenbonbon** [comment]
Thanks, so the problem we run into there is:
We build the url inside the app, so you only need to put in the base url (https://192.168.5.263), nothing more. (Project ID and password belong to the both textfield underneath
Obviously now, that is not clear/failsafe, I will think a bit about the best solution there

**Comment by 3tyh86qvt** [comment]
I have tried to only paste the base url, as you had told me, still hopeless :/

Thank you very much for developing a public open source app and for your support :D

**Comment by m-idler** [comment]
In general it seems to be problematic/impossible to use the iOS long tap copy/paste "context" menu on all fields (url, projectId, password).

**Comment by Hustenbonbon** [comment]
In current master, pasting is implemented. Will be included in Release 2.0 which is currently getting wrapped up
