### ISSUE TITLE
support older iOS versions

### ISSUE THREAD

**Issue by call-me-matt** [mayflower/PayForMe#29]
Hello! Installed nextcloud's cospend and wanted to try out PayForMe. Unfortunately it requires a newer iOS than I have on my phone. Is that a hard requirement or could it be possible to support also older versions?

**Comment by Hustenbonbon** [comment]
Hey, PayForMe is completely written in SwiftUI, which works unfortunately only on iOS 13 upwards, which means the oldest iPhone working should be the 6S.
Sorry, but there is no way to make it available for older device other than creating every screen completely new.

**Comment by call-me-matt** [comment]
I understand that, thank you for your feedback.
