### ISSUE TITLE
Overwrite the last bill

### ISSUE THREAD

**Issue by admclhome** [mayflower/PayForMe#31]
Since few days the app overwrites the last bill, when I create a new one. I had think that are to much entries in the list and I had delete some. But thats not the reason. My Project have 68 bills. I had also delete the Project and create the connection new. But no success. The App sync all entries with the Nextcloud Cospend, but when I create a new one, the same problem. But when I create a bill in Nextcloud, the App sync that an show it correctly. In my other Project with lower number of bills, everything is right. 
I use the IOS App in version 1.4 and it is installed on IOS 13.6.

**Comment by Hustenbonbon** [comment]
Super strange! So this problem started occuring without any update of the app, right?
I know that iOS 13.6 made some changes to SwiftUI, but something like this should never happen. Will look into it.
If you feel comfortable with that, it could be quite helpful if you could send me access to your project via hustenbonbon@posteo.de

**Comment by admclhome** [comment]
so... for completness.. 
My mail to the maintainers..
Dear,
Thanks for your reply. Now I'am really confused. I export and import the project for a playground, but in the imported version, every thing is fine. The Bills can be create.
I send you an guest account with member rights for the main project and also an guest account for the copy als Maintainer.
-------------
I solved the problem when I export the poject to csv and import it to cospend. I don't know whats the reasion, but after that you can create bill after bill. Thanks to the Maintainers for here Work

**Comment by Hustenbonbon** [comment]
Hey, so everything is fine now? 
Still something that shouldn't have happened. Didn't come to it this week, but will have a look at the corresponding code soon
