### ISSUE TITLE
PayForMe only overwrittes the last entry

### ISSUE THREAD

**Issue by messma** [mayflower/PayForMe#32]
Since a few weeks PayForMe only edits the last entry.
This means when you create a bill's the first one is overwritten.

**Comment by clay9247** [comment]
Same for me. Any news on this?

**Comment by clay9247** [comment]
Same here. Workaround mentioned in https://github.com/mayflower/PayForMe/issues/31#issuecomment-667697832 worked for me.

**Comment by messma** [comment]
Worked for me too.
Thanks.
