### ISSUE TITLE
It is not possible to add an ihatemoney project.

### ISSUE THREAD

**Issue by netpages** [mayflower/PayForMe#35]
It is not possible to add an iHateMoney project (self-hosted) to the app.
In the UI it is not possible to switch from Cospend to iHateMoney, the button does not seem to be active.

iPhone 12 Pro, iOS 14.3

**Comment by Hustenbonbon** [comment]
Hey,

just checked and I can confirm this.
Will work on a fix soon, but not over the holidays, I hope you understand.

Until then, if you can get a Cospend project, adding a Cospend project first and then an iHateMoney project,  it still works.

Sorry for the bug, and merry christmas (if you are celebrating :-) )

**Comment by Hustenbonbon** [comment]
I found the reason, it is unfortunately an underlying SwiftUI bug. I pushed a hotfix, it will be automatically published after Apple's review

**Comment by netpages** [comment]
Sorry for that late late reply, works now as expected.
Thanks
