### ISSUE TITLE
Sort (and maybe filter) listed bill

### ISSUE THREAD

**Issue by syntion** [mayflower/PayForMe#39]
I am using the app in combination with Cospend on Nextcloud. I have several hundred bills in one of my projects and they are probably sorted by the date I added bill. This make it very difficult to check if I forgot to add an older bill. 

So It would be great if I could at least sort the list them by the date of bill. Furthermore some kind of filtering or search would make this even simpler.

**Comment by Hustenbonbon** [comment]
This is a good Idea, we also had in the beginning. We then scrapped it for the MVP and never thought of adding it later on - I'll add it as soon as I find the time (which unfortunately could take a while)

**Comment by Hustenbonbon** [comment]
Added a possibility to sort bills in the latest version which is about to be released in the next days!
