### ISSUE TITLE
Recurring expenses are listed multiple times with each occurrence

### ISSUE THREAD

**Issue by aniqueta** [mayflower/PayForMe#40]
If there's a recurring expense created in Cospend, then PayForMe will show the recurring item multiple times when the next occurrence occurs. 

For example, if there's a monthly expense set on 1 January, then PayForMe show it once on that date. This is good. However, when 1 February, occurs, it will show it twice in the list for 1 February and then immediately below it for 1 January. On 1 March, it will show it three times for March, February, and January. The dates are correct, it's the ordering of the list that creates confusion. This are also no inconsistencies with calculations. It is just confusing to the end user. 

My hypothesis is that Cospend updates the the recurring expense on each occurrence date, and then PayForMe sees all of the occurrences again as new in the feed. So, this is probably a simple matter of sorting the PayForMe list by time of expense and not time of update to the expense entry, or something like that. Thanks!

**Comment by Hustenbonbon** [comment]
yes, this is a smaller thing because we sort for last updated - assuming users want to see the most recently changed (by other users) bills first. I have no immediate, small fix in mind, but will try to think about one. Alternative would be to switch to sorting by last created or date of the bill.

**Comment by Hustenbonbon** [comment]
Since then we added the option to sort by changed or original bill date, so this issue is outdated
