### ISSUE TITLE
Ordering reversed

### ISSUE THREAD

**Issue by aniqueta** [mayflower/PayForMe#44]
Thanks for the update to chose between expense date and modified date. Right now, for me, both lists are sorted with oldest first, newest last. So one has to scroll for quite some time to see the latest entries.

**Comment by Hustenbonbon** [comment]
Wow, sorry, and thanks for reporting! Hotfix will be pushed to Apple today! Oldest first is obviously not what I planned

**Comment by Hustenbonbon** [comment]
Hotfix is on the way!

**Comment by Hustenbonbon** [comment]
Hotfix is released

**Comment by Hustenbonbon** [comment]
It behaved differently in iOS 14 and iOS 15 - added different styling for both versions
