### ISSUE TITLE
Did not work since new update

### ISSUE THREAD

**Issue by 601deluxe** [mayflower/PayForMe#46]
Since the last update the app did not work very well. You can not add a new transaction. The App will show green button but nothing happens. Costs/transactions will be shown and update from server but you don’t can make a new cost in the app.

please help/update was failed

**Comment by Hustenbonbon** [comment]
Hi, I unfortunately mixed a bugifx with some rewrite-stuff that broke everything. Rolling back now, so the new version 2.3.4 (currently in progress) is the same as old 2.3.2

**Comment by 601deluxe** [comment]
Hi, many thanks for your feedback. When can we reload the app from appstore?

**Comment by Hustenbonbon** [comment]
Hi, the new old version is available again

**Comment by 601deluxe** [comment]
Many thanks for the fast support. It runs perfect again.
