### ISSUE TITLE
Custom names/aliases for projects?

### ISSUE THREAD

**Issue by mrclschstr** [mayflower/PayForMe#49]
First of all: I love your project, keep up the good work!

I have a small issue using PayForMe with the current Cospend release 1.4.3. Adding a project using the new [Share Links](https://github.com/eneiluj/cospend-nc/issues/9) works fine, but results in a 32 charater project name, for example `02fdec61f6ba7eb944e06b326b6a3eb9`. Unfortunately this is very confusing having multiple projects. Would it be possible to assign custom names/aliases for the projects? This would help the overview a lot!

**Comment by Hustenbonbon** [comment]
Hi, it seems to be that something changed on how newer Cospend-Versions handle project names. I will try to look into it, but currently I don't find a lot of time for this project. Feedback from users definitely helps though!

**Comment by Hustenbonbon** [comment]
Hi, I just checked in. The authentification way changed, so PayForMe confuses the access key with the project name now. I can't get the project name from the backend, but I'll try to add a field for an own name

**Comment by mrclschstr** [comment]
You need a separate API call to get the project name: https://github.com/eneiluj/cospend-nc/issues/9#issuecomment-1060050904

**Comment by Hustenbonbon** [comment]
Thanks for researching! I was in contact with @eneiluj in parallel and he told me about it too. I'm working on a fix, but can't promise a timeline, as I'm quite occupied with my dayjob currently.

**Comment by Hustenbonbon** [comment]
I'm very happy though to show anyone who wants to write a bit swift code how I imagine a solution for this fix so they can create a PR
