### ISSUE TITLE
Real project name doesn't show

### ISSUE THREAD

**Issue by justinlimbo** [mayflower/PayForMe#50]
The name of the cospend projects only show in these cryptical numbers/letters.

I tried removing and re-adding the project, but still the same. 

I think this happend first one or two releases ago. I'm on the latest 2.3.4. version now.

![image](https://user-images.githubusercontent.com/97830287/156737338-97fcfd14-bc65-4d60-8af9-e645185525f2.jpeg)

**Comment by justinlimbo** [comment]
I guess this is the same issue as this. https://github.com/mayflower/PayForMe/issues/49

Only seeing this now. Sorry for duplicating the issue here.

**Comment by Hustenbonbon** [comment]
Hey, thanks for reaching out still! I'll answer in the other issue!
