### ISSUE TITLE
IHateMoney - Server can't be found

### ISSUE THREAD

**Issue by rkowalewski** [mayflower/PayForMe#52]
Hello,

after installing the most recent PayForMe Client in iOS (v.2.3.5) I cannot connect to a new project anymore.

How to reproduce:
- create a test project on the hosted [IHateMoney](https://ihatemoney.org/) site.
- Add it in the PayForMe Client

Reply: Can't find server.

It is similar to #48, however, the underlying root cause should be different. Furthermore it is IHateyMoney, not Cospent.

Edit: Old projects (already added) still work. Just the initial setup to add a new project is an issue.

**Comment by rkowalewski** [comment]
May it be possible to revert to the previous version in the app store until someone found enough time to fix that?

**Comment by Hustenbonbon** [comment]
Hi, 
I see, I wanted to change something only for Cospend, but it seems to have affected iHateMoney. Unfortunately, I can't auto-revert it (App Store stuff), and I can't fix it before next week, because I'm currently travelling. 
Will do this with high priority next week though

**Comment by rkowalewski** [comment]
Sure, thank you for the update.

**Comment by rkowalewski** [comment]
Sure, thank you for the update.

**Comment by rkowalewski** [comment]
Hi,

sorry for the repeating question. However, as essential functionality is not available, did you have a change to look at it?

**Comment by Hustenbonbon** [comment]
if you want to test the fix before the release (would be much appreciated!), there is the invite link for the beta-testers:
https://testflight.apple.com/join/o6XAnU9g

**Comment by rkowalewski** [comment]
I am aware of that and appreciate your OS contribution. Thank you. I installed the test version, played around with it and everything seems to work.

**Comment by Hustenbonbon** [comment]
Thanks for testing & reporting the issue. I wonder how many people had this issue, I have no idea about how many people use the app with CoSpend and how many with iHateMoney

**Comment by Hustenbonbon** [comment]
The fix is also in the new public version now

**Comment by Finebouche** [comment]
Hi, I am experiencing the exact same problem with version 2.3.7

**Comment by Hustenbonbon** [comment]
As this issue was reported fixed with version 2.3.7, let's continue in #53
