### ISSUE TITLE
App not in AppStore anymore

### ISSUE THREAD

**Issue by Chrispikaan** [mayflower/PayForMe#65]
Hello, I'm from the Netherlands and I don't see the PayForMe app in de iOS appstore anymore.

On my iPhone 14 Pro with iOS 15.5.1 I still have the app, but I tried to download it on another iPhone with iOS 15.5.1 (in The Netherlands) I can't find it.
When I share a link to the appstore it's giving me an error: App is not available in your country or region.

**Comment by Hustenbonbon** [comment]
It's a billing problem - I'm working on getting it back on, hopefully today

**Comment by Hustenbonbon** [comment]
No problem, thanks for notifying
